//! Readiness gate for the trainmarks benchmark (DataTreehouse): do all six
//! trainmarks queries actually *execute* on the storage/WCOJ-backed
//! `HornBackend`, on real generated data?
//!
//! This is a correctness/feature smoke, NOT a timing bench. It loads the
//! generated `medium.nt` (~100K triples) and runs q1..q6 verbatim from the
//! trainmarks query files, reporting OK + a result summary or the error.
//!
//! Requires the data + queries generated by `target/trainmarks/generate_data.py`:
//!
//! ```text
//! TRAINMARKS_DIR=target/trainmarks cargo test -p horndb-sparql --release \
//!     --test trainmarks_smoke -- --ignored --nocapture
//! ```

use horndb_sparql::api::{execute_query, execute_update, QueryAnswer};
use horndb_sparql::exec::horn::HornBackend;
use oxttl::NTriplesParser;
use std::io::BufReader;
use std::path::PathBuf;
use std::time::Instant;

fn dir() -> PathBuf {
    PathBuf::from(std::env::var("TRAINMARKS_DIR").unwrap_or_else(|_| "target/trainmarks".into()))
}

fn load_nt(backend: &mut HornBackend, path: &PathBuf) {
    let reader = BufReader::new(std::fs::File::open(path).expect("open nt"));
    let mut batch = Vec::new();
    for t in NTriplesParser::new().for_reader(reader) {
        let t = t.expect("parse nt");
        batch.push((
            oxrdf::Term::from(t.subject),
            oxrdf::Term::from(t.predicate),
            t.object,
        ));
    }
    backend.insert_oxrdf_batch(batch).expect("load batch");
}

#[test]
#[ignore = "needs generated trainmarks data; run explicitly with --ignored"]
fn trainmarks_queries_execute() {
    let d = dir();
    let nt = d.join("data/medium.nt");
    let qdir = d.join("queries");

    let mut backend = HornBackend::new();
    let t = Instant::now();
    load_nt(&mut backend, &nt);
    eprintln!(
        "[load] {} triples in {:.2}s",
        backend.len(),
        t.elapsed().as_secs_f64()
    );

    let queries = [
        "q1_count",
        "q2_customer_orders",
        "q3_join_3_entities",
        "q4_optional_aggregation",
        "q5_construct",
        "q6_delete_insert",
    ];

    let mut failures = 0;
    for name in queries {
        let sql = std::fs::read_to_string(qdir.join(format!("{name}.rq"))).expect("read query");
        // Updates (q6) start with DELETE/INSERT after any PREFIX lines.
        let is_update = sql.lines().any(|l| {
            let u = l.trim_start().to_uppercase();
            u.starts_with("DELETE") || u.starts_with("INSERT")
        });

        let t = Instant::now();
        if is_update {
            match execute_update(&sql, &mut backend) {
                Ok(()) => eprintln!(
                    "[ OK ] {name}: UPDATE applied in {:.3}s (store now {} triples)",
                    t.elapsed().as_secs_f64(),
                    backend.len()
                ),
                Err(e) => {
                    eprintln!("[FAIL] {name}: {e}");
                    failures += 1;
                }
            }
        } else {
            match execute_query(&sql, &backend) {
                Ok(ans) => {
                    let summary = match &ans {
                        QueryAnswer::Solutions { vars, rows } => {
                            let first = rows.first().map(|r| {
                                vars.iter()
                                    .map(|v| {
                                        format!(
                                            "{v}={}",
                                            r.get(v).map(|t| format!("{t:?}")).unwrap_or_default()
                                        )
                                    })
                                    .collect::<Vec<_>>()
                                    .join(", ")
                            });
                            format!(
                                "{} rows; vars [{}]; first: {{{}}}",
                                rows.len(),
                                vars.join(", "),
                                first.unwrap_or_default()
                            )
                        }
                        QueryAnswer::Boolean(b) => format!("ASK -> {b}"),
                        QueryAnswer::Triples(v) => format!("CONSTRUCT -> {} triples", v.len()),
                        QueryAnswer::Explanation { .. } => "explain".into(),
                    };
                    eprintln!(
                        "[ OK ] {name}: {:.3}s | {summary}",
                        t.elapsed().as_secs_f64()
                    );
                }
                Err(e) => {
                    eprintln!("[FAIL] {name}: {e}");
                    failures += 1;
                }
            }
        }
    }

    assert_eq!(
        failures, 0,
        "{failures} trainmarks queries failed to execute"
    );
}
