//! Emit one `fn fire_<id>(...)` per rule + a `pub const RULES: &[CompiledRule]`.

use crate::codegen::parse::{RuleSpec, Slot};
use crate::codegen::plan::{plan_rule, BoundSource, Plan, SlotPlan, SlotPos};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

pub fn emit_all(rules: &[RuleSpec]) -> TokenStream {
    let mut fns = Vec::new();
    let mut table_entries = Vec::new();
    let mut id_lits = Vec::new();

    for r in rules {
        let fn_ident = format_ident!("fire_{}", sanitize_id(&r.id));
        let id_str = &r.id;
        id_lits.push(quote! { #id_str });

        if r.delegate {
            // No body — runtime calls ClosureBackend instead. Still emit a fn
            // so the rule table has a uniform signature; the fn returns empty.
            fns.push(quote! {
                #[doc = concat!("DELEGATED: ", #id_str, " is handled by ClosureBackend.")]
                pub fn #fn_ident(
                    _store: &dyn crate::store::TripleStore,
                    _delta: &crate::delta::Delta,
                ) -> crate::delta::Delta {
                    crate::delta::Delta::new()
                }
            });
            table_entries.push(quote! {
                CompiledRule {
                    id: #id_str,
                    delegated: true,
                    fire: #fn_ident,
                    body_predicates: &[],
                    wildcard_predicate: false,
                }
            });
            continue;
        }

        let plan = plan_rule(r);
        let body_preds = body_predicate_fields(r);
        let body_has_var_predicate = r
            .body
            .iter()
            .any(|pat| matches!(pat.p, crate::codegen::parse::Slot::Var(_)));
        let body_tokens = emit_rule_body(r, &plan);

        fns.push(quote! {
            #[doc = concat!("Compiled OWL 2 RL rule: ", #id_str)]
            #[allow(unused_variables)]
            pub fn #fn_ident(
                store: &dyn crate::store::TripleStore,
                _delta: &crate::delta::Delta,
            ) -> crate::delta::Delta {
                use crate::types::Triple;
                use crate::provenance::Provenance;
                let v = store.vocab();
                let mut out = crate::delta::Delta::new();
                #body_tokens
                out
            }
        });

        let preds_tokens = body_preds.iter().map(|f| {
            let id = format_ident!("{}", f);
            quote! { (|v: &crate::vocab::Vocabulary| v.#id) as PredAccessor }
        });
        table_entries.push(quote! {
            CompiledRule {
                id: #id_str,
                delegated: false,
                fire: #fn_ident,
                body_predicates: &[ #( #preds_tokens ),* ],
                wildcard_predicate: #body_has_var_predicate,
            }
        });
    }

    let n = rules.len();
    quote! {
        // AUTOGENERATED by build.rs from rules.toml — DO NOT EDIT.

        pub type FireFn = fn(
            &dyn crate::store::TripleStore,
            &crate::delta::Delta,
        ) -> crate::delta::Delta;

        pub type PredAccessor = fn(&crate::vocab::Vocabulary) -> crate::types::TermId;

        pub struct CompiledRule {
            pub id: &'static str,
            pub delegated: bool,
            pub fire: FireFn,
            /// Predicate-IDs the rule body reads. Used by semi-naïve driver
            /// to skip rules whose predicates are not dirty.
            pub body_predicates: &'static [PredAccessor],
            /// True iff the rule's body contains a pattern whose predicate
            /// slot is a variable (e.g. `?s ?p ?o` in eq-rep-s/p/o). Such a
            /// rule reads triples with *any* predicate, so the dirty-predicate
            /// prune in [`crate::engine::rule_relevant`] must treat it as
            /// always-relevant whenever the dirty set is non-empty.
            pub wildcard_predicate: bool,
        }

        pub const RULE_COUNT: usize = #n;
        pub const RULE_IDS: &[&str] = &[ #( #id_lits ),* ];

        #( #fns )*

        pub const RULES: &[CompiledRule] = &[
            #( #table_entries ),*
        ];
    }
}

fn emit_rule_body(rule: &RuleSpec, plan: &Plan) -> TokenStream {
    emit_step(rule, plan, 0)
}

fn emit_step(rule: &RuleSpec, plan: &Plan, depth: usize) -> TokenStream {
    if depth == plan.steps.len() {
        return emit_head(rule);
    }
    let step = &plan.steps[depth];
    let triple_var = format_ident!("__t{}", depth);

    let inner = emit_step(rule, plan, depth + 1);

    // Generate bindings from the iterated triple. For Fresh slots, bind the
    // variable to the corresponding field of the iterated Triple.
    let bind_s = bind_for(&step.s, &triple_var, SlotPos::S);
    let bind_p = bind_for(&step.p, &triple_var, SlotPos::P);
    let bind_o = bind_for(&step.o, &triple_var, SlotPos::O);

    // Same-pattern repeated-variable equality filter (e.g. `?x ?p ?x`).
    let intra_eq_filter = intra_step_equality_filter(step, &triple_var);

    if depth == 0 {
        // Leading step: choose iteration source.
        let leading_iter = match &step.p {
            SlotPlan::Bound(BoundSource::Vocab(field)) => {
                let id = format_ident!("{}", field);
                quote! { store.scan_predicate(v.#id) }
            }
            SlotPlan::Bound(BoundSource::Var(_))
            | SlotPlan::Fresh(_)
            | SlotPlan::SameAsEarlierSlot { .. } => {
                // No Stage-1 non-delegated rule needs variable-predicate
                // leading iteration. prp-trp uses it but is delegated.
                panic!(
                    "rule {}: leading pattern predicate must be a vocabulary term in Stage 1",
                    rule.id
                );
            }
        };
        // Inline filter for any leading slot that is vocab-bound (s or o).
        let filter = filter_for_leading(&step.s, &step.o, &triple_var);
        quote! {
            for #triple_var in #leading_iter {
                #filter
                #intra_eq_filter
                #bind_s
                #bind_p
                #bind_o
                #inner
            }
        }
    } else {
        // Probing step.
        let s_arg = probe_arg(&step.s);
        let o_arg = probe_arg(&step.o);
        match &step.p {
            // Variable predicate not yet bound — scan every predicate partition.
            // Used by eq-rep-s / eq-rep-o whose second pattern is `?s ?p ?o`.
            SlotPlan::Fresh(_) => {
                quote! {
                    for #triple_var in store.probe_any_predicate(#s_arg, #o_arg) {
                        #intra_eq_filter
                        #bind_s
                        #bind_p
                        #bind_o
                        #inner
                    }
                }
            }
            // Predicate is either a vocab term or a previously-bound variable.
            _ => {
                let p_arg = probe_predicate(&step.p, rule);
                quote! {
                    for #triple_var in store.probe(#s_arg, #p_arg, #o_arg) {
                        #intra_eq_filter
                        #bind_s
                        #bind_p
                        #bind_o
                        #inner
                    }
                }
            }
        }
    }
}

fn bind_for(slot: &SlotPlan, triple_var: &proc_macro2::Ident, pos: SlotPos) -> TokenStream {
    match slot {
        SlotPlan::Fresh(name) => {
            let var = format_ident!("{}", name);
            let field = match pos {
                SlotPos::S => quote! { s },
                SlotPos::P => quote! { p },
                SlotPos::O => quote! { o },
            };
            quote! { let #var = #triple_var.#field; }
        }
        SlotPlan::Bound(_) | SlotPlan::SameAsEarlierSlot { .. } => quote! {},
    }
}

/// Emit `if __tN.<slot> != __tN.<earlier> { continue; }` for every slot in
/// this step that re-uses a variable already introduced earlier in the same
/// triple pattern (e.g. `?x ?p ?x` — second `?x` must equal the first).
fn intra_step_equality_filter(
    step: &crate::codegen::plan::PlanStep,
    triple_var: &proc_macro2::Ident,
) -> TokenStream {
    let mut checks = Vec::new();
    for (pos, slot) in [
        (SlotPos::S, &step.s),
        (SlotPos::P, &step.p),
        (SlotPos::O, &step.o),
    ] {
        if let SlotPlan::SameAsEarlierSlot { earlier, .. } = slot {
            let this = field_ident(pos);
            let other = field_ident(*earlier);
            checks.push(quote! {
                if #triple_var.#this != #triple_var.#other { continue; }
            });
        }
    }
    quote! { #( #checks )* }
}

fn field_ident(pos: SlotPos) -> proc_macro2::Ident {
    match pos {
        SlotPos::S => format_ident!("s"),
        SlotPos::P => format_ident!("p"),
        SlotPos::O => format_ident!("o"),
    }
}

fn filter_for_leading(s: &SlotPlan, o: &SlotPlan, triple: &proc_macro2::Ident) -> TokenStream {
    let s_chk = match s {
        SlotPlan::Bound(BoundSource::Vocab(field)) => {
            let id = format_ident!("{}", field);
            Some(quote! { if #triple.s != v.#id { continue; } })
        }
        _ => None,
    };
    let o_chk = match o {
        SlotPlan::Bound(BoundSource::Vocab(field)) => {
            let id = format_ident!("{}", field);
            Some(quote! { if #triple.o != v.#id { continue; } })
        }
        _ => None,
    };
    let s_chk = s_chk.unwrap_or_default();
    let o_chk = o_chk.unwrap_or_default();
    quote! { #s_chk #o_chk }
}

fn probe_arg(slot: &SlotPlan) -> TokenStream {
    match slot {
        SlotPlan::Fresh(_) | SlotPlan::SameAsEarlierSlot { .. } => quote! { None },
        SlotPlan::Bound(BoundSource::Var(name)) => {
            let id = format_ident!("{}", name);
            quote! { Some(#id) }
        }
        SlotPlan::Bound(BoundSource::Vocab(field)) => {
            let id = format_ident!("{}", field);
            quote! { Some(v.#id) }
        }
    }
}

fn probe_predicate(slot: &SlotPlan, rule: &RuleSpec) -> TokenStream {
    match slot {
        SlotPlan::Bound(BoundSource::Vocab(field)) => {
            let id = format_ident!("{}", field);
            quote! { v.#id }
        }
        SlotPlan::Bound(BoundSource::Var(name)) => {
            let id = format_ident!("{}", name);
            quote! { #id }
        }
        SlotPlan::Fresh(_) | SlotPlan::SameAsEarlierSlot { .. } => panic!(
            "rule {}: probe step predicate cannot be a fresh variable",
            rule.id
        ),
    }
}

fn emit_head(rule: &RuleSpec) -> TokenStream {
    let s = head_expr(&rule.head.s);
    let p = head_expr(&rule.head.p);
    let o = head_expr(&rule.head.o);
    let id = &rule.id;

    // Build a SmallVec of premise triples (the `__t0`, `__t1`, ...).
    let premise_idents: Vec<_> = (0..rule.body.len())
        .map(|i| format_ident!("__t{}", i))
        .collect();
    let premise_count = rule.body.len();

    quote! {
        let head = Triple::new(#s, #p, #o);
        if !store.contains(&head) && !out.contains(&head) {
            let mut premises = ::smallvec::SmallVec::<[Triple; 4]>::with_capacity(#premise_count);
            #( premises.push(#premise_idents); )*
            out.insert(head, Provenance { rule_id: #id, premises });
        }
    }
}

fn head_expr(slot: &Slot) -> TokenStream {
    match slot {
        Slot::Var(name) => {
            let id = format_ident!("{}", name);
            quote! { #id }
        }
        Slot::Vocab(v) => {
            let id = format_ident!("{}", v.field);
            quote! { v.#id }
        }
    }
}

fn body_predicate_fields(rule: &RuleSpec) -> Vec<&'static str> {
    let mut out = Vec::new();
    for pat in &rule.body {
        if let Slot::Vocab(v) = &pat.p {
            if !out.contains(&v.field) {
                out.push(v.field);
            }
        }
    }
    out
}

fn sanitize_id(id: &str) -> String {
    id.replace(['-', ':'], "_")
}
