//! Build-time rule codegen. Reads rules.toml, validates, emits generated_rules.rs.
//!
//! Stage 1: parse-and-emit-stub. Real per-rule emission lands in Task 10.

#[path = "codegen/mod.rs"]
mod codegen;

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let rules_path = manifest_dir.join("rules.toml");
    println!("cargo:rerun-if-changed={}", rules_path.display());
    println!("cargo:rerun-if-changed=codegen/mod.rs");
    println!("cargo:rerun-if-changed=codegen/parse.rs");
    println!("cargo:rerun-if-changed=codegen/emit.rs");
    println!("cargo:rerun-if-changed=codegen/plan.rs");

    let rules = match codegen::parse::parse_file(&rules_path) {
        Ok(rs) => rs,
        Err(e) => {
            eprintln!("FAILED to parse rules.toml: {e:#}");
            std::process::exit(1);
        }
    };

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("generated_rules.rs");

    // Stage-1 stub: emit a const counting the rules and a `pub const RULES: &[&str]`.
    // Real per-rule emission is Task 10.
    let mut out = String::new();
    out.push_str("// AUTOGENERATED by build.rs from rules.toml — DO NOT EDIT.\n\n");
    out.push_str(&format!("pub const RULE_COUNT: usize = {};\n", rules.len()));
    out.push_str("pub const RULE_IDS: &[&str] = &[\n");
    for r in &rules {
        out.push_str(&format!("    {:?},\n", r.id));
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("writing generated_rules.rs");
}
