#!/usr/bin/env python3
"""Generate an RDFox Datalog ruleset from HornDB's crates/owlrl/rules.toml.

The point: make RDFox fire exactly the rules HornDB's compiled engine fires,
so a HornDB-vs-RDFox materialization comparison is apples-to-apples. The
closure-count parity gate in compare-rdfox.sh validates the translation.

Inclusion policy (driven by each rule's head):
  * OMIT rules whose head asserts inconsistency (head.o == "owl:Nothing").
    They derive no normal triples, so they cannot affect the closure count.
  * OMIT rules with an empty body (eq-ref): not expressible as a Datalog rule,
    and HornDB does not materialize reflexive owl:sameAs as explicit triples.
  * INCLUDE everything else, including delegate="closure" rules (HornDB does
    these via GraphBLAS; RDFox via native recursion) and sameAs-deriving
    prp-fp/prp-ifp.

Usage:  gen_ruleset.py [--rules PATH]   # writes .dlog to stdout
"""
import argparse
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    sys.exit("gen_ruleset.py requires Python 3.11+ (tomllib)")

PREFIXES = {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
}


def load_rules(path):
    with open(path, "rb") as fh:
        return tomllib.load(fh).get("rule", [])


def term(v):
    # Variables ("?x") and prefixed names ("rdf:type") pass through to RDFox
    # Datalog verbatim. Full IRIs (<...>) and literals ("...") are not used by
    # rules.toml today and would need explicit handling — fail loudly if seen.
    if v.startswith("<") or v.startswith('"'):
        raise ValueError(f"unsupported term form (full IRI or literal): {v!r}")
    return v


def atom(t):
    return f"[{term(t['s'])}, {term(t['p'])}, {term(t['o'])}]"


def is_inconsistency(rule):
    return rule.get("head", {}).get("o") == "owl:Nothing"


def is_empty_body(rule):
    return not rule.get("body")


def included(rule):
    return not is_empty_body(rule) and not is_inconsistency(rule)


def rule_to_dlog(rule):
    head = atom(rule["head"])
    body = ", ".join(atom(b) for b in rule["body"])
    return f"{head} :- {body} ."


def generate(rules):
    kept = [r for r in rules if included(r)]
    omitted = [r for r in rules if not included(r)]
    lines = []
    lines.append("# GENERATED by scripts/bench/gen_ruleset.py from crates/owlrl/rules.toml.")
    lines.append("# Do not edit by hand. RDFox runs this so it fires exactly HornDB's rules.")
    lines.append("# INTERNAL benchmarking artifact.")
    lines.append("#")
    lines.append("# OMITTED rules (head asserts inconsistency, or empty body — no derived triples):")
    for r in omitted:
        why = "inconsistency (owl:Nothing)" if is_inconsistency(r) else "empty body"
        lines.append(f"#   - {r['id']}: {why}")
    lines.append("")
    for pfx, iri in PREFIXES.items():
        lines.append(f"@prefix {pfx}: <{iri}> .")
    lines.append("")
    for r in kept:
        assert "id" in r, f"rule missing id: {r}"
        cid = r["id"]
        delegate = r.get("delegate")
        suffix = f"  (delegate: {delegate})" if delegate else ""
        lines.append(f"# {cid}{suffix}")
        lines.append(rule_to_dlog(r))
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    default = Path(__file__).resolve().parents[2] / "crates" / "owlrl" / "rules.toml"
    ap.add_argument("--rules", type=Path, default=default)
    args = ap.parse_args(argv)
    sys.stdout.write(generate(load_rules(args.rules)))


if __name__ == "__main__":
    main()
